client_config_backend: settings
client_config:
  client_id: "1071083412982-e52a6pug7o6r0l78511fbiulgb3djrdp.apps.googleusercontent.com"
  client_secret: "m7vFL7RYR87LX9R6WYEC8iVT"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install